import org.junit.Test;
import sample.spring.boot.Application;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yamashiro-r' at '17/01/31 22:55' with Gradle 3.2.1
 *
 * @author yamashiro-r, @date 17/01/31 22:55
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        final Application classUnderTest = new Application();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
