/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yamashiro-r' at '16/12/23 18:23' with Gradle 3.2.1
 *
 * @author yamashiro-r, @date 16/12/23 18:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
